language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  include:
    - php: '5.5'
      env:
        - 'DB_CONNECTION=mysql DB_HOST=localhost DB_DATABASE=codedatabase DB_USERNAME=travis'
    - php: '5.6'
      env:
        - 'DB_CONNECTION=mysql DB_HOST=localhost DB_DATABASE=codedatabase DB_USERNAME=travis'
    - php: '7.0'
      env:
        - 'DB_CONNECTION=mysql DB_HOST=localhost DB_DATABASE=codedatabase DB_USERNAME=travis'


before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  -  mysql -utravis -e "create database codedatabase;"

script:
  - vendor/bin/phpunit