language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

env:
  global:
    - 'DB_CONNECTION=mysql'
    - 'DB_HOST=localhost'
    - 'DB_DATABASE=codedatabase'
    - 'DB_USERNAME=travis'

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  -  mysql -utravis -e "create database codedatabase;"

script:
  - vendor/bin/phpunit